Repository stackb/rules_proto, pull requests merged in 2018-12, with the labels that each got.

#13 Remove travis hook
  .travis.yml
  README.md
  tools/exgen/header.tpl
Labels: size/M

#19 Add javax annotation API dependency to //java:proto_deps
  java/BUILD.bazel
Labels: size/XS

#22 Remove old buildozer rule
  closure/BUILD.bazel
Labels: size/S

#24 Move dart-specific dep rules into dart/ package.
  dart/deps.bzl
  deps.bzl
Labels: size/L

#25 Update rules go for bazel 0.20.0 compat
  deps.bzl
Labels: size/XS

#27 Update rules_closure
  .bazelrc
  Makefile
  README.md
  closure/README.md
  closure/closure_proto_library.bzl
  closure/deps.bzl
  deps.bzl
  github.com/grpc/grpc-web/deps.bzl
  github.com/improbable-eng/ts-protoc-gen/deps.bzl
  github.com/stackb/grpc.js/deps.bzl
  tools/exgen/closure.go
Labels: size/M

#29 Adapt to latest bazel changes (fix #14)
  compile.bzl
Labels: ok-to-test, size/XS

#30 Update csharp dependencies.
  WORKSPACE
  csharp/nuget/README.md
  csharp/nuget/grpc.bzl
  csharp/nuget/nuget.bzl
  csharp/nuget/packages.bzl
  csharp/nuget/protobuf.bzl
  csharp/nuget/regenerate_packages.sh
  deps.bzl
Labels: size/L
