Repository stackb/rules_proto, pull requests merged in 2019-02, with the labels that each got.

#42 [deps.bzl] Update com_github_grpc_grpc to v1.18.0
  deps.bzl
Labels: size/XS

#44 Update com_google_protobuf version to v3.6.1.3
  WORKSPACE
  deps.bzl
Labels: size/S

#49 Fix github archive stripPrefix ref
  Makefile
  deps.bzl
Labels: size/XS

#50 Propagate transitive and verbose flags in gogo_* rules
  github.com/gogo/protobuf/README.md
  github.com/gogo/protobuf/gogo_grpc_library.bzl
  github.com/gogo/protobuf/gogo_proto_library.bzl
  github.com/gogo/protobuf/gogofast_grpc_library.bzl
  github.com/gogo/protobuf/gogofast_proto_library.bzl
  github.com/gogo/protobuf/gogofaster_grpc_library.bzl
  github.com/gogo/protobuf/gogofaster_proto_library.bzl
  go/BUILD.bazel
  tools/exgen/gogo.go
Labels: size/M

#53 Remove usage of "+" with dict in Starlark
  compile.bzl
Labels: size/XS
